// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetesingressnginx.inputs.AutoscalingBehaviorArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AutoscalingArgs extends com.pulumi.resources.ResourceArgs {

    public static final AutoscalingArgs Empty = new AutoscalingArgs();

    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    @Import(name="controllerAutoscalingBehavior")
    private @Nullable Output<AutoscalingBehaviorArgs> controllerAutoscalingBehavior;

    public Optional<Output<AutoscalingBehaviorArgs>> controllerAutoscalingBehavior() {
        return Optional.ofNullable(this.controllerAutoscalingBehavior);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="maxReplicas")
    private @Nullable Output<Integer> maxReplicas;

    public Optional<Output<Integer>> maxReplicas() {
        return Optional.ofNullable(this.maxReplicas);
    }

    @Import(name="minReplicas")
    private @Nullable Output<Integer> minReplicas;

    public Optional<Output<Integer>> minReplicas() {
        return Optional.ofNullable(this.minReplicas);
    }

    @Import(name="targetCPUUtilizationPercentage")
    private @Nullable Output<Integer> targetCPUUtilizationPercentage;

    public Optional<Output<Integer>> targetCPUUtilizationPercentage() {
        return Optional.ofNullable(this.targetCPUUtilizationPercentage);
    }

    @Import(name="targetMemoryUtilizationPercentage")
    private @Nullable Output<Integer> targetMemoryUtilizationPercentage;

    public Optional<Output<Integer>> targetMemoryUtilizationPercentage() {
        return Optional.ofNullable(this.targetMemoryUtilizationPercentage);
    }

    private AutoscalingArgs() {}

    private AutoscalingArgs(AutoscalingArgs $) {
        this.annotations = $.annotations;
        this.controllerAutoscalingBehavior = $.controllerAutoscalingBehavior;
        this.enabled = $.enabled;
        this.maxReplicas = $.maxReplicas;
        this.minReplicas = $.minReplicas;
        this.targetCPUUtilizationPercentage = $.targetCPUUtilizationPercentage;
        this.targetMemoryUtilizationPercentage = $.targetMemoryUtilizationPercentage;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AutoscalingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AutoscalingArgs $;

        public Builder() {
            $ = new AutoscalingArgs();
        }

        public Builder(AutoscalingArgs defaults) {
            $ = new AutoscalingArgs(Objects.requireNonNull(defaults));
        }

        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        public Builder controllerAutoscalingBehavior(@Nullable Output<AutoscalingBehaviorArgs> controllerAutoscalingBehavior) {
            $.controllerAutoscalingBehavior = controllerAutoscalingBehavior;
            return this;
        }

        public Builder controllerAutoscalingBehavior(AutoscalingBehaviorArgs controllerAutoscalingBehavior) {
            return controllerAutoscalingBehavior(Output.of(controllerAutoscalingBehavior));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder maxReplicas(@Nullable Output<Integer> maxReplicas) {
            $.maxReplicas = maxReplicas;
            return this;
        }

        public Builder maxReplicas(Integer maxReplicas) {
            return maxReplicas(Output.of(maxReplicas));
        }

        public Builder minReplicas(@Nullable Output<Integer> minReplicas) {
            $.minReplicas = minReplicas;
            return this;
        }

        public Builder minReplicas(Integer minReplicas) {
            return minReplicas(Output.of(minReplicas));
        }

        public Builder targetCPUUtilizationPercentage(@Nullable Output<Integer> targetCPUUtilizationPercentage) {
            $.targetCPUUtilizationPercentage = targetCPUUtilizationPercentage;
            return this;
        }

        public Builder targetCPUUtilizationPercentage(Integer targetCPUUtilizationPercentage) {
            return targetCPUUtilizationPercentage(Output.of(targetCPUUtilizationPercentage));
        }

        public Builder targetMemoryUtilizationPercentage(@Nullable Output<Integer> targetMemoryUtilizationPercentage) {
            $.targetMemoryUtilizationPercentage = targetMemoryUtilizationPercentage;
            return this;
        }

        public Builder targetMemoryUtilizationPercentage(Integer targetMemoryUtilizationPercentage) {
            return targetMemoryUtilizationPercentage(Output.of(targetMemoryUtilizationPercentage));
        }

        public AutoscalingArgs build() {
            return $;
        }
    }

}
