// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetesingressnginx.inputs.AutoscalingTemplatePodsMetricArgs;
import com.pulumi.kubernetesingressnginx.inputs.AutoscalingTemplatePodsTargetArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AutoscalingTemplatePodsArgs extends com.pulumi.resources.ResourceArgs {

    public static final AutoscalingTemplatePodsArgs Empty = new AutoscalingTemplatePodsArgs();

    @Import(name="metric")
    private @Nullable Output<AutoscalingTemplatePodsMetricArgs> metric;

    public Optional<Output<AutoscalingTemplatePodsMetricArgs>> metric() {
        return Optional.ofNullable(this.metric);
    }

    @Import(name="target")
    private @Nullable Output<AutoscalingTemplatePodsTargetArgs> target;

    public Optional<Output<AutoscalingTemplatePodsTargetArgs>> target() {
        return Optional.ofNullable(this.target);
    }

    private AutoscalingTemplatePodsArgs() {}

    private AutoscalingTemplatePodsArgs(AutoscalingTemplatePodsArgs $) {
        this.metric = $.metric;
        this.target = $.target;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AutoscalingTemplatePodsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AutoscalingTemplatePodsArgs $;

        public Builder() {
            $ = new AutoscalingTemplatePodsArgs();
        }

        public Builder(AutoscalingTemplatePodsArgs defaults) {
            $ = new AutoscalingTemplatePodsArgs(Objects.requireNonNull(defaults));
        }

        public Builder metric(@Nullable Output<AutoscalingTemplatePodsMetricArgs> metric) {
            $.metric = metric;
            return this;
        }

        public Builder metric(AutoscalingTemplatePodsMetricArgs metric) {
            return metric(Output.of(metric));
        }

        public Builder target(@Nullable Output<AutoscalingTemplatePodsTargetArgs> target) {
            $.target = target;
            return this;
        }

        public Builder target(AutoscalingTemplatePodsTargetArgs target) {
            return target(Output.of(target));
        }

        public AutoscalingTemplatePodsArgs build() {
            return $;
        }
    }

}
