// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetesingressnginx.inputs.AutoscalingBehaviorScalingArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AutoscalingBehaviorArgs extends com.pulumi.resources.ResourceArgs {

    public static final AutoscalingBehaviorArgs Empty = new AutoscalingBehaviorArgs();

    @Import(name="scaleDown")
    private @Nullable Output<AutoscalingBehaviorScalingArgs> scaleDown;

    public Optional<Output<AutoscalingBehaviorScalingArgs>> scaleDown() {
        return Optional.ofNullable(this.scaleDown);
    }

    @Import(name="scaleUp")
    private @Nullable Output<AutoscalingBehaviorScalingArgs> scaleUp;

    public Optional<Output<AutoscalingBehaviorScalingArgs>> scaleUp() {
        return Optional.ofNullable(this.scaleUp);
    }

    private AutoscalingBehaviorArgs() {}

    private AutoscalingBehaviorArgs(AutoscalingBehaviorArgs $) {
        this.scaleDown = $.scaleDown;
        this.scaleUp = $.scaleUp;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AutoscalingBehaviorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AutoscalingBehaviorArgs $;

        public Builder() {
            $ = new AutoscalingBehaviorArgs();
        }

        public Builder(AutoscalingBehaviorArgs defaults) {
            $ = new AutoscalingBehaviorArgs(Objects.requireNonNull(defaults));
        }

        public Builder scaleDown(@Nullable Output<AutoscalingBehaviorScalingArgs> scaleDown) {
            $.scaleDown = scaleDown;
            return this;
        }

        public Builder scaleDown(AutoscalingBehaviorScalingArgs scaleDown) {
            return scaleDown(Output.of(scaleDown));
        }

        public Builder scaleUp(@Nullable Output<AutoscalingBehaviorScalingArgs> scaleUp) {
            $.scaleUp = scaleUp;
            return this;
        }

        public Builder scaleUp(AutoscalingBehaviorScalingArgs scaleUp) {
            return scaleUp(Output.of(scaleUp));
        }

        public AutoscalingBehaviorArgs build() {
            return $;
        }
    }

}
