// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AutoscalingTemplatePodsTargetArgs extends com.pulumi.resources.ResourceArgs {

    public static final AutoscalingTemplatePodsTargetArgs Empty = new AutoscalingTemplatePodsTargetArgs();

    @Import(name="averageValue")
    private @Nullable Output<String> averageValue;

    public Optional<Output<String>> averageValue() {
        return Optional.ofNullable(this.averageValue);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private AutoscalingTemplatePodsTargetArgs() {}

    private AutoscalingTemplatePodsTargetArgs(AutoscalingTemplatePodsTargetArgs $) {
        this.averageValue = $.averageValue;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AutoscalingTemplatePodsTargetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AutoscalingTemplatePodsTargetArgs $;

        public Builder() {
            $ = new AutoscalingTemplatePodsTargetArgs();
        }

        public Builder(AutoscalingTemplatePodsTargetArgs defaults) {
            $ = new AutoscalingTemplatePodsTargetArgs(Objects.requireNonNull(defaults));
        }

        public Builder averageValue(@Nullable Output<String> averageValue) {
            $.averageValue = averageValue;
            return this;
        }

        public Builder averageValue(String averageValue) {
            return averageValue(Output.of(averageValue));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public AutoscalingTemplatePodsTargetArgs build() {
            return $;
        }
    }

}
