// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetesingressnginx.inputs.AutoscalingBehaviorScalingPolicyArgs;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AutoscalingBehaviorScalingArgs extends com.pulumi.resources.ResourceArgs {

    public static final AutoscalingBehaviorScalingArgs Empty = new AutoscalingBehaviorScalingArgs();

    @Import(name="policies")
    private @Nullable Output<List<AutoscalingBehaviorScalingPolicyArgs>> policies;

    public Optional<Output<List<AutoscalingBehaviorScalingPolicyArgs>>> policies() {
        return Optional.ofNullable(this.policies);
    }

    @Import(name="stabilizationWindowSeconds")
    private @Nullable Output<Integer> stabilizationWindowSeconds;

    public Optional<Output<Integer>> stabilizationWindowSeconds() {
        return Optional.ofNullable(this.stabilizationWindowSeconds);
    }

    private AutoscalingBehaviorScalingArgs() {}

    private AutoscalingBehaviorScalingArgs(AutoscalingBehaviorScalingArgs $) {
        this.policies = $.policies;
        this.stabilizationWindowSeconds = $.stabilizationWindowSeconds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AutoscalingBehaviorScalingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AutoscalingBehaviorScalingArgs $;

        public Builder() {
            $ = new AutoscalingBehaviorScalingArgs();
        }

        public Builder(AutoscalingBehaviorScalingArgs defaults) {
            $ = new AutoscalingBehaviorScalingArgs(Objects.requireNonNull(defaults));
        }

        public Builder policies(@Nullable Output<List<AutoscalingBehaviorScalingPolicyArgs>> policies) {
            $.policies = policies;
            return this;
        }

        public Builder policies(List<AutoscalingBehaviorScalingPolicyArgs> policies) {
            return policies(Output.of(policies));
        }

        public Builder policies(AutoscalingBehaviorScalingPolicyArgs... policies) {
            return policies(List.of(policies));
        }

        public Builder stabilizationWindowSeconds(@Nullable Output<Integer> stabilizationWindowSeconds) {
            $.stabilizationWindowSeconds = stabilizationWindowSeconds;
            return this;
        }

        public Builder stabilizationWindowSeconds(Integer stabilizationWindowSeconds) {
            return stabilizationWindowSeconds(Output.of(stabilizationWindowSeconds));
        }

        public AutoscalingBehaviorScalingArgs build() {
            return $;
        }
    }

}
