// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetesingressnginx.inputs.ControllerRollingUpdateArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ControllerUpdateStrategyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ControllerUpdateStrategyArgs Empty = new ControllerUpdateStrategyArgs();

    @Import(name="rollingUpdate")
    private @Nullable Output<ControllerRollingUpdateArgs> rollingUpdate;

    public Optional<Output<ControllerRollingUpdateArgs>> rollingUpdate() {
        return Optional.ofNullable(this.rollingUpdate);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private ControllerUpdateStrategyArgs() {}

    private ControllerUpdateStrategyArgs(ControllerUpdateStrategyArgs $) {
        this.rollingUpdate = $.rollingUpdate;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ControllerUpdateStrategyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ControllerUpdateStrategyArgs $;

        public Builder() {
            $ = new ControllerUpdateStrategyArgs();
        }

        public Builder(ControllerUpdateStrategyArgs defaults) {
            $ = new ControllerUpdateStrategyArgs(Objects.requireNonNull(defaults));
        }

        public Builder rollingUpdate(@Nullable Output<ControllerRollingUpdateArgs> rollingUpdate) {
            $.rollingUpdate = rollingUpdate;
            return this;
        }

        public Builder rollingUpdate(ControllerRollingUpdateArgs rollingUpdate) {
            return rollingUpdate(Output.of(rollingUpdate));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ControllerUpdateStrategyArgs build() {
            return $;
        }
    }

}
