// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ControllerMetricsServiceArgs extends com.pulumi.resources.ResourceArgs {

    public static final ControllerMetricsServiceArgs Empty = new ControllerMetricsServiceArgs();

    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    @Import(name="clusterIP")
    private @Nullable Output<String> clusterIP;

    public Optional<Output<String>> clusterIP() {
        return Optional.ofNullable(this.clusterIP);
    }

    @Import(name="externalIPs")
    private @Nullable Output<List<String>> externalIPs;

    public Optional<Output<List<String>>> externalIPs() {
        return Optional.ofNullable(this.externalIPs);
    }

    @Import(name="externalTrafficPolicy")
    private @Nullable Output<String> externalTrafficPolicy;

    public Optional<Output<String>> externalTrafficPolicy() {
        return Optional.ofNullable(this.externalTrafficPolicy);
    }

    @Import(name="loadBalancerIPs")
    private @Nullable Output<String> loadBalancerIPs;

    public Optional<Output<String>> loadBalancerIPs() {
        return Optional.ofNullable(this.loadBalancerIPs);
    }

    @Import(name="loadBalancerSourceRanges")
    private @Nullable Output<List<String>> loadBalancerSourceRanges;

    public Optional<Output<List<String>>> loadBalancerSourceRanges() {
        return Optional.ofNullable(this.loadBalancerSourceRanges);
    }

    @Import(name="nodePort")
    private @Nullable Output<String> nodePort;

    public Optional<Output<String>> nodePort() {
        return Optional.ofNullable(this.nodePort);
    }

    @Import(name="servicePort")
    private @Nullable Output<Integer> servicePort;

    public Optional<Output<Integer>> servicePort() {
        return Optional.ofNullable(this.servicePort);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private ControllerMetricsServiceArgs() {}

    private ControllerMetricsServiceArgs(ControllerMetricsServiceArgs $) {
        this.annotations = $.annotations;
        this.clusterIP = $.clusterIP;
        this.externalIPs = $.externalIPs;
        this.externalTrafficPolicy = $.externalTrafficPolicy;
        this.loadBalancerIPs = $.loadBalancerIPs;
        this.loadBalancerSourceRanges = $.loadBalancerSourceRanges;
        this.nodePort = $.nodePort;
        this.servicePort = $.servicePort;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ControllerMetricsServiceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ControllerMetricsServiceArgs $;

        public Builder() {
            $ = new ControllerMetricsServiceArgs();
        }

        public Builder(ControllerMetricsServiceArgs defaults) {
            $ = new ControllerMetricsServiceArgs(Objects.requireNonNull(defaults));
        }

        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        public Builder clusterIP(@Nullable Output<String> clusterIP) {
            $.clusterIP = clusterIP;
            return this;
        }

        public Builder clusterIP(String clusterIP) {
            return clusterIP(Output.of(clusterIP));
        }

        public Builder externalIPs(@Nullable Output<List<String>> externalIPs) {
            $.externalIPs = externalIPs;
            return this;
        }

        public Builder externalIPs(List<String> externalIPs) {
            return externalIPs(Output.of(externalIPs));
        }

        public Builder externalIPs(String... externalIPs) {
            return externalIPs(List.of(externalIPs));
        }

        public Builder externalTrafficPolicy(@Nullable Output<String> externalTrafficPolicy) {
            $.externalTrafficPolicy = externalTrafficPolicy;
            return this;
        }

        public Builder externalTrafficPolicy(String externalTrafficPolicy) {
            return externalTrafficPolicy(Output.of(externalTrafficPolicy));
        }

        public Builder loadBalancerIPs(@Nullable Output<String> loadBalancerIPs) {
            $.loadBalancerIPs = loadBalancerIPs;
            return this;
        }

        public Builder loadBalancerIPs(String loadBalancerIPs) {
            return loadBalancerIPs(Output.of(loadBalancerIPs));
        }

        public Builder loadBalancerSourceRanges(@Nullable Output<List<String>> loadBalancerSourceRanges) {
            $.loadBalancerSourceRanges = loadBalancerSourceRanges;
            return this;
        }

        public Builder loadBalancerSourceRanges(List<String> loadBalancerSourceRanges) {
            return loadBalancerSourceRanges(Output.of(loadBalancerSourceRanges));
        }

        public Builder loadBalancerSourceRanges(String... loadBalancerSourceRanges) {
            return loadBalancerSourceRanges(List.of(loadBalancerSourceRanges));
        }

        public Builder nodePort(@Nullable Output<String> nodePort) {
            $.nodePort = nodePort;
            return this;
        }

        public Builder nodePort(String nodePort) {
            return nodePort(Output.of(nodePort));
        }

        public Builder servicePort(@Nullable Output<Integer> servicePort) {
            $.servicePort = servicePort;
            return this;
        }

        public Builder servicePort(Integer servicePort) {
            return servicePort(Output.of(servicePort));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ControllerMetricsServiceArgs build() {
            return $;
        }
    }

}
