// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ControllerRollingUpdateArgs extends com.pulumi.resources.ResourceArgs {

    public static final ControllerRollingUpdateArgs Empty = new ControllerRollingUpdateArgs();

    @Import(name="maxUnavailable")
    private @Nullable Output<Integer> maxUnavailable;

    public Optional<Output<Integer>> maxUnavailable() {
        return Optional.ofNullable(this.maxUnavailable);
    }

    private ControllerRollingUpdateArgs() {}

    private ControllerRollingUpdateArgs(ControllerRollingUpdateArgs $) {
        this.maxUnavailable = $.maxUnavailable;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ControllerRollingUpdateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ControllerRollingUpdateArgs $;

        public Builder() {
            $ = new ControllerRollingUpdateArgs();
        }

        public Builder(ControllerRollingUpdateArgs defaults) {
            $ = new ControllerRollingUpdateArgs(Objects.requireNonNull(defaults));
        }

        public Builder maxUnavailable(@Nullable Output<Integer> maxUnavailable) {
            $.maxUnavailable = maxUnavailable;
            return this;
        }

        public Builder maxUnavailable(Integer maxUnavailable) {
            return maxUnavailable(Output.of(maxUnavailable));
        }

        public ControllerRollingUpdateArgs build() {
            return $;
        }
    }

}
