// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ControllerServiceInternalArgs extends com.pulumi.resources.ResourceArgs {

    public static final ControllerServiceInternalArgs Empty = new ControllerServiceInternalArgs();

    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Set external traffic policy to: &#34;Local&#34; to preserve source IP on providers supporting it. Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
     * 
     */
    @Import(name="externalTrafficPolicy")
    private @Nullable Output<String> externalTrafficPolicy;

    /**
     * @return Set external traffic policy to: &#34;Local&#34; to preserve source IP on providers supporting it. Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
     * 
     */
    public Optional<Output<String>> externalTrafficPolicy() {
        return Optional.ofNullable(this.externalTrafficPolicy);
    }

    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    @Import(name="loadBalancerIPs")
    private @Nullable Output<String> loadBalancerIPs;

    public Optional<Output<String>> loadBalancerIPs() {
        return Optional.ofNullable(this.loadBalancerIPs);
    }

    /**
     * Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
     * 
     */
    @Import(name="loadBalancerSourceRanges")
    private @Nullable Output<List<String>> loadBalancerSourceRanges;

    /**
     * @return Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
     * 
     */
    public Optional<Output<List<String>>> loadBalancerSourceRanges() {
        return Optional.ofNullable(this.loadBalancerSourceRanges);
    }

    private ControllerServiceInternalArgs() {}

    private ControllerServiceInternalArgs(ControllerServiceInternalArgs $) {
        this.annotations = $.annotations;
        this.enabled = $.enabled;
        this.externalTrafficPolicy = $.externalTrafficPolicy;
        this.labels = $.labels;
        this.loadBalancerIPs = $.loadBalancerIPs;
        this.loadBalancerSourceRanges = $.loadBalancerSourceRanges;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ControllerServiceInternalArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ControllerServiceInternalArgs $;

        public Builder() {
            $ = new ControllerServiceInternalArgs();
        }

        public Builder(ControllerServiceInternalArgs defaults) {
            $ = new ControllerServiceInternalArgs(Objects.requireNonNull(defaults));
        }

        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param externalTrafficPolicy Set external traffic policy to: &#34;Local&#34; to preserve source IP on providers supporting it. Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
         * 
         * @return builder
         * 
         */
        public Builder externalTrafficPolicy(@Nullable Output<String> externalTrafficPolicy) {
            $.externalTrafficPolicy = externalTrafficPolicy;
            return this;
        }

        /**
         * @param externalTrafficPolicy Set external traffic policy to: &#34;Local&#34; to preserve source IP on providers supporting it. Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
         * 
         * @return builder
         * 
         */
        public Builder externalTrafficPolicy(String externalTrafficPolicy) {
            return externalTrafficPolicy(Output.of(externalTrafficPolicy));
        }

        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        public Builder loadBalancerIPs(@Nullable Output<String> loadBalancerIPs) {
            $.loadBalancerIPs = loadBalancerIPs;
            return this;
        }

        public Builder loadBalancerIPs(String loadBalancerIPs) {
            return loadBalancerIPs(Output.of(loadBalancerIPs));
        }

        /**
         * @param loadBalancerSourceRanges Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
         * 
         * @return builder
         * 
         */
        public Builder loadBalancerSourceRanges(@Nullable Output<List<String>> loadBalancerSourceRanges) {
            $.loadBalancerSourceRanges = loadBalancerSourceRanges;
            return this;
        }

        /**
         * @param loadBalancerSourceRanges Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
         * 
         * @return builder
         * 
         */
        public Builder loadBalancerSourceRanges(List<String> loadBalancerSourceRanges) {
            return loadBalancerSourceRanges(Output.of(loadBalancerSourceRanges));
        }

        /**
         * @param loadBalancerSourceRanges Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
         * 
         * @return builder
         * 
         */
        public Builder loadBalancerSourceRanges(String... loadBalancerSourceRanges) {
            return loadBalancerSourceRanges(List.of(loadBalancerSourceRanges));
        }

        public ControllerServiceInternalArgs build() {
            return $;
        }
    }

}
