// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KedaScaledObjectArgs extends com.pulumi.resources.ResourceArgs {

    public static final KedaScaledObjectArgs Empty = new KedaScaledObjectArgs();

    /**
     * Custom annotations for ScaledObject resource.
     * 
     */
    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    /**
     * @return Custom annotations for ScaledObject resource.
     * 
     */
    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    private KedaScaledObjectArgs() {}

    private KedaScaledObjectArgs(KedaScaledObjectArgs $) {
        this.annotations = $.annotations;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KedaScaledObjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KedaScaledObjectArgs $;

        public Builder() {
            $ = new KedaScaledObjectArgs();
        }

        public Builder(KedaScaledObjectArgs defaults) {
            $ = new KedaScaledObjectArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param annotations Custom annotations for ScaledObject resource.
         * 
         * @return builder
         * 
         */
        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        /**
         * @param annotations Custom annotations for ScaledObject resource.
         * 
         * @return builder
         * 
         */
        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        public KedaScaledObjectArgs build() {
            return $;
        }
    }

}
