// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetesingressnginx.inputs.AutoscalingBehaviorArgs;
import com.pulumi.kubernetesingressnginx.inputs.KedaScaledObjectArgs;
import com.pulumi.kubernetesingressnginx.inputs.KedaTriggerArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KedaArgs extends com.pulumi.resources.ResourceArgs {

    public static final KedaArgs Empty = new KedaArgs();

    /**
     * apiVersion changes with keda 1.x vs 2.x: 2.x = keda.sh/v1alpha1, 1.x = keda.k8s.io/v1alpha1.
     * 
     */
    @Import(name="apiVersion")
    private @Nullable Output<String> apiVersion;

    /**
     * @return apiVersion changes with keda 1.x vs 2.x: 2.x = keda.sh/v1alpha1, 1.x = keda.k8s.io/v1alpha1.
     * 
     */
    public Optional<Output<String>> apiVersion() {
        return Optional.ofNullable(this.apiVersion);
    }

    @Import(name="behavior")
    private @Nullable Output<AutoscalingBehaviorArgs> behavior;

    public Optional<Output<AutoscalingBehaviorArgs>> behavior() {
        return Optional.ofNullable(this.behavior);
    }

    @Import(name="cooldownPeriod")
    private @Nullable Output<Integer> cooldownPeriod;

    public Optional<Output<Integer>> cooldownPeriod() {
        return Optional.ofNullable(this.cooldownPeriod);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="maxReplicas")
    private @Nullable Output<Integer> maxReplicas;

    public Optional<Output<Integer>> maxReplicas() {
        return Optional.ofNullable(this.maxReplicas);
    }

    @Import(name="minReplicas")
    private @Nullable Output<Integer> minReplicas;

    public Optional<Output<Integer>> minReplicas() {
        return Optional.ofNullable(this.minReplicas);
    }

    @Import(name="pollingInterval")
    private @Nullable Output<Integer> pollingInterval;

    public Optional<Output<Integer>> pollingInterval() {
        return Optional.ofNullable(this.pollingInterval);
    }

    @Import(name="restoreToOriginalReplicaCount")
    private @Nullable Output<Boolean> restoreToOriginalReplicaCount;

    public Optional<Output<Boolean>> restoreToOriginalReplicaCount() {
        return Optional.ofNullable(this.restoreToOriginalReplicaCount);
    }

    @Import(name="scaledObject")
    private @Nullable Output<KedaScaledObjectArgs> scaledObject;

    public Optional<Output<KedaScaledObjectArgs>> scaledObject() {
        return Optional.ofNullable(this.scaledObject);
    }

    @Import(name="triggers")
    private @Nullable Output<List<KedaTriggerArgs>> triggers;

    public Optional<Output<List<KedaTriggerArgs>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    private KedaArgs() {}

    private KedaArgs(KedaArgs $) {
        this.apiVersion = $.apiVersion;
        this.behavior = $.behavior;
        this.cooldownPeriod = $.cooldownPeriod;
        this.enabled = $.enabled;
        this.maxReplicas = $.maxReplicas;
        this.minReplicas = $.minReplicas;
        this.pollingInterval = $.pollingInterval;
        this.restoreToOriginalReplicaCount = $.restoreToOriginalReplicaCount;
        this.scaledObject = $.scaledObject;
        this.triggers = $.triggers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KedaArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KedaArgs $;

        public Builder() {
            $ = new KedaArgs();
        }

        public Builder(KedaArgs defaults) {
            $ = new KedaArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiVersion apiVersion changes with keda 1.x vs 2.x: 2.x = keda.sh/v1alpha1, 1.x = keda.k8s.io/v1alpha1.
         * 
         * @return builder
         * 
         */
        public Builder apiVersion(@Nullable Output<String> apiVersion) {
            $.apiVersion = apiVersion;
            return this;
        }

        /**
         * @param apiVersion apiVersion changes with keda 1.x vs 2.x: 2.x = keda.sh/v1alpha1, 1.x = keda.k8s.io/v1alpha1.
         * 
         * @return builder
         * 
         */
        public Builder apiVersion(String apiVersion) {
            return apiVersion(Output.of(apiVersion));
        }

        public Builder behavior(@Nullable Output<AutoscalingBehaviorArgs> behavior) {
            $.behavior = behavior;
            return this;
        }

        public Builder behavior(AutoscalingBehaviorArgs behavior) {
            return behavior(Output.of(behavior));
        }

        public Builder cooldownPeriod(@Nullable Output<Integer> cooldownPeriod) {
            $.cooldownPeriod = cooldownPeriod;
            return this;
        }

        public Builder cooldownPeriod(Integer cooldownPeriod) {
            return cooldownPeriod(Output.of(cooldownPeriod));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder maxReplicas(@Nullable Output<Integer> maxReplicas) {
            $.maxReplicas = maxReplicas;
            return this;
        }

        public Builder maxReplicas(Integer maxReplicas) {
            return maxReplicas(Output.of(maxReplicas));
        }

        public Builder minReplicas(@Nullable Output<Integer> minReplicas) {
            $.minReplicas = minReplicas;
            return this;
        }

        public Builder minReplicas(Integer minReplicas) {
            return minReplicas(Output.of(minReplicas));
        }

        public Builder pollingInterval(@Nullable Output<Integer> pollingInterval) {
            $.pollingInterval = pollingInterval;
            return this;
        }

        public Builder pollingInterval(Integer pollingInterval) {
            return pollingInterval(Output.of(pollingInterval));
        }

        public Builder restoreToOriginalReplicaCount(@Nullable Output<Boolean> restoreToOriginalReplicaCount) {
            $.restoreToOriginalReplicaCount = restoreToOriginalReplicaCount;
            return this;
        }

        public Builder restoreToOriginalReplicaCount(Boolean restoreToOriginalReplicaCount) {
            return restoreToOriginalReplicaCount(Output.of(restoreToOriginalReplicaCount));
        }

        public Builder scaledObject(@Nullable Output<KedaScaledObjectArgs> scaledObject) {
            $.scaledObject = scaledObject;
            return this;
        }

        public Builder scaledObject(KedaScaledObjectArgs scaledObject) {
            return scaledObject(Output.of(scaledObject));
        }

        public Builder triggers(@Nullable Output<List<KedaTriggerArgs>> triggers) {
            $.triggers = triggers;
            return this;
        }

        public Builder triggers(List<KedaTriggerArgs> triggers) {
            return triggers(Output.of(triggers));
        }

        public Builder triggers(KedaTriggerArgs... triggers) {
            return triggers(List.of(triggers));
        }

        public KedaArgs build() {
            return $;
        }
    }

}
