// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetesingressnginx;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.kubernetesingressnginx.IngressControllerArgs;
import com.pulumi.kubernetesingressnginx.Utilities;
import com.pulumi.kubernetesingressnginx.outputs.ReleaseStatus;
import javax.annotation.Nullable;

/**
 * Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
 * 
 */
@ResourceType(type="kubernetes-ingress-nginx:index:IngressController")
public class IngressController extends com.pulumi.resources.ComponentResource {
    /**
     * Detailed information about the status of the underlying Helm deployment.
     * 
     */
    @Export(name="status", refs={ReleaseStatus.class}, tree="[0]")
    private Output<ReleaseStatus> status;

    /**
     * @return Detailed information about the status of the underlying Helm deployment.
     * 
     */
    public Output<ReleaseStatus> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IngressController(java.lang.String name) {
        this(name, IngressControllerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IngressController(java.lang.String name, @Nullable IngressControllerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IngressController(java.lang.String name, @Nullable IngressControllerArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("kubernetes-ingress-nginx:index:IngressController", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static IngressControllerArgs makeArgs(@Nullable IngressControllerArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? IngressControllerArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
