# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .ingress_controller import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "chart-ingress-nginx",
  "mod": "index",
  "fqn": "pulumi_chart_ingress_nginx",
  "classes": {
   "chart-ingress-nginx:index:IngressController": "IngressController"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "chart-ingress-nginx",
  "token": "pulumi:providers:chart-ingress-nginx",
  "fqn": "pulumi_chart_ingress_nginx",
  "class": "Provider"
 }
]
"""
)
