// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class AutoscalingTemplatePodsArgs : global::Pulumi.ResourceArgs
    {
        [Input("metric")]
        public Input<Inputs.AutoscalingTemplatePodsMetricArgs>? Metric { get; set; }

        [Input("target")]
        public Input<Inputs.AutoscalingTemplatePodsTargetArgs>? Target { get; set; }

        public AutoscalingTemplatePodsArgs()
        {
        }
        public static new AutoscalingTemplatePodsArgs Empty => new AutoscalingTemplatePodsArgs();
    }
}
