// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class AutoscalingTemplatePodsMetricArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        public AutoscalingTemplatePodsMetricArgs()
        {
        }
        public static new AutoscalingTemplatePodsMetricArgs Empty => new AutoscalingTemplatePodsMetricArgs();
    }
}
