// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class AutoscalingBehaviorArgs : global::Pulumi.ResourceArgs
    {
        [Input("scaleDown")]
        public Input<Inputs.AutoscalingBehaviorScalingArgs>? ScaleDown { get; set; }

        [Input("scaleUp")]
        public Input<Inputs.AutoscalingBehaviorScalingArgs>? ScaleUp { get; set; }

        public AutoscalingBehaviorArgs()
        {
        }
        public static new AutoscalingBehaviorArgs Empty => new AutoscalingBehaviorArgs();
    }
}
