// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class ControllerRollingUpdateArgs : global::Pulumi.ResourceArgs
    {
        [Input("maxUnavailable")]
        public Input<int>? MaxUnavailable { get; set; }

        public ControllerRollingUpdateArgs()
        {
        }
        public static new ControllerRollingUpdateArgs Empty => new ControllerRollingUpdateArgs();
    }
}
