// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class ControllerImageArgs : Pulumi.ResourceArgs
    {
        [Input("allowPrivilegeEscalation")]
        public Input<bool>? AllowPrivilegeEscalation { get; set; }

        [Input("digest")]
        public Input<string>? Digest { get; set; }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("pullPolicy")]
        public Input<string>? PullPolicy { get; set; }

        [Input("readOnlyRootFilesystem")]
        public Input<bool>? ReadOnlyRootFilesystem { get; set; }

        [Input("registry")]
        public Input<string>? Registry { get; set; }

        /// <summary>
        /// for backwards compatibility consider setting the full image url via the repository value below use *either* current default registry/image or repository format or installing will fail.
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        [Input("runAsNonRoot")]
        public Input<bool>? RunAsNonRoot { get; set; }

        [Input("runAsUser")]
        public Input<string>? RunAsUser { get; set; }

        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public ControllerImageArgs()
        {
        }
    }
}
