// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class ControllerUpdateStrategyArgs : global::Pulumi.ResourceArgs
    {
        [Input("rollingUpdate")]
        public Input<Inputs.ControllerRollingUpdateArgs>? RollingUpdate { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ControllerUpdateStrategyArgs()
        {
        }
        public static new ControllerUpdateStrategyArgs Empty => new ControllerUpdateStrategyArgs();
    }
}
