// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class ControllerHostPortArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("ports")]
        public Input<Inputs.ControllerHostPortPortsArgs>? Ports { get; set; }

        public ControllerHostPortArgs()
        {
        }
        public static new ControllerHostPortArgs Empty => new ControllerHostPortArgs();
    }
}
