// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ChartIngressNginx.Inputs
{

    public sealed class ControllerServiceAccountArgs : Pulumi.ResourceArgs
    {
        [Input("automountServiceAccountToken")]
        public Input<bool>? AutomountServiceAccountToken { get; set; }

        [Input("create")]
        public Input<bool>? Create { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public ControllerServiceAccountArgs()
        {
        }
    }
}
