// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesIngressNginx.Inputs
{

    public sealed class ControllerRBACArgs : global::Pulumi.ResourceArgs
    {
        [Input("create")]
        public Input<bool>? Create { get; set; }

        [Input("scope")]
        public Input<bool>? Scope { get; set; }

        public ControllerRBACArgs()
        {
        }
        public static new ControllerRBACArgs Empty => new ControllerRBACArgs();
    }
}
