// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ChartIngressNginx.Inputs
{

    public sealed class ControllerServiceNodePortsArgs : Pulumi.ResourceArgs
    {
        [Input("http")]
        public Input<string>? Http { get; set; }

        [Input("https")]
        public Input<string>? Https { get; set; }

        [Input("tcp")]
        private InputMap<ImmutableDictionary<string, string>>? _tcp;
        public InputMap<ImmutableDictionary<string, string>> Tcp
        {
            get => _tcp ?? (_tcp = new InputMap<ImmutableDictionary<string, string>>());
            set => _tcp = value;
        }

        [Input("udp")]
        private InputMap<ImmutableDictionary<string, string>>? _udp;
        public InputMap<ImmutableDictionary<string, string>> Udp
        {
            get => _udp ?? (_udp = new InputMap<ImmutableDictionary<string, string>>());
            set => _udp = value;
        }

        public ControllerServiceNodePortsArgs()
        {
        }
    }
}
